# TODO
name: Appdome buid-2secure
description: TODO
branding:
  icon: 'bluetooth'
  color: 'blue'

inputs:
  APPDOME_API_TOKEN:
    description: 'Appdome API key'
    default: '!'
    required: true
  APP_FILE:
    description: 'APK file'
    default: '!'
    required: true
  FUSION_SET_ID:
    description: "Appdome Fusion Set Id"
    default: '!'
    required: true
  SIGN_OPTIONS:
    type: choice
    description: Android Sign Options
    options: 
    - AUTO_SIGNING
    - PRIVATE_SIGNING
    - AUTO_DEV_SIGNING
    required: true
  KEYSTORE_FILE:
    description: 'Keystore file'
    default: '!'
    required: false
  MOBILE_PROVISION_PROFILE_FILE:
    description: ''
    default: '!'
    required: false
  ENTITLEMENTS_FILE:
    description: ''
    default: '!'
    required: false
  KEYSTORE_PASSWORD:
    description: ''
    default: '!'
    required: false
  KEYSTORE_ALIAS:
    description: 'keystore alias'
    default: '!'
    required: false
  KEYSTORE_KEY_PASSWORD:
    description: 'keystore key password'
    default: '!'
    required: false
  SIGN_FINGERPRINT:
    description: 'signing sha1 fingerprint'
    default: '!'
    required: false
  GOOGLE-PLAY-SIGNING:
    description: 'Google Play App Signing program'
    type: boolean
    default: false
    required: false
  TEAM-ID:
    description: 'Insert your team-id. This line is optional and may be removed when working on a personal workspace.'
    default: '!'
    required: false

runs:
  using: "composite"
  steps:
    - name: Cloning appdome-api-python github repository
      uses: actions/checkout@master
      with:
        repository: Appdome/appdome-api-python
        ref: refs/heads/main
        path: appdome
    - name: Install requirements
      run: sudo apt update | sudo apt install python3-pip | sudo pip3 install -r appdome/requirements.txt
      shell: bash   
    - name: Cloning actions
      uses: actions/checkout@master
      with:
        repository: nirappdome/appdome_android_action
        ref: refs/heads/main
        path: actions
    - name: permissions
      run: chmod +x ./actions/actions/appdome_build_sign.py | chmod +x ./actions/actions/files_manager.py
      shell: bash
    - name: Run download action files
      run: python3 ./actions/actions/files_manager.py ${{ inputs.APP_FILE }} ${{ inputs.KEYSTORE_FILE }} ${{ inputs.MOBILE_PROVISION_PROFILE_FILE }} ${{ inputs.ENTITLEMENTS_FILE }}
      shell: bash
    - name: Run appdome bash action files
      run: python3 ./actions/actions/appdome_build_sign.py ${{ inputs.SIGN_OPTIONS }} ${{ inputs.APPDOME_API_TOKEN }} ${{ inputs.FUSION_SET_ID }} ${{ inputs.KEYSTORE_PASSWORD }} ${{ inputs.KEYSTORE_ALIAS }} ${{ inputs.KEYSTORE_KEY_PASSWORD }} ${{ inputs.TEAM-ID }} ${{ inputs.GOOGLE-PLAY-SIGNING }} ${{ inputs.SIGN_FINGERPRINT }} 
      shell: bash
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: workflow-artifacts
        path: ./output/ # path to output folder
